### PR TITLE
Add Sentry SDK

### PR DESCRIPTION
**Pull request by HazAT**
Sentry ✅  ✅  ✅  ✅
😄

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
🔢

**Comment by KrauseFx** [comment]
You can merge 👍

**Comment by HazAT** [comment]
@KrauseFx How?
screenshot 2018-05-22 21 45 30

**Comment by HazAT** [comment]
Ups, nevermind, just saw the invite. Thanks 👍

**Pull request merged**
